name: flutter_first_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.5
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - ./lib/assets/sample.json
    - ./lib/assets/images/
    
  fonts:
    # [FiraCode](https://github.com/tonsky/FiraCode)
    - family: FiraCode
      fonts:
        - asset: ./lib/assets/fonts/FiraCode-VF.ttf

    # [jf open 粉圓](https://github.com/justfont/open-huninn-font)
    - family: OpenHuninn
      fonts:
        - asset: ./lib/assets/fonts/OpenHuninn-1.1.ttf


